baseURL: 'https://stratagem360ai.github.io/AIGenesis/'
languageCode: 'en-us'
title: 'AI Genesis Blogs>_ '
theme: ["PaperMod"]
sectionPagesMenu: main
tags: [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features: [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "twitter"
      url: "https://x.com/d_suhas"
    - name: "substack"
      url: "https://stratagem360.substack.com"
params:
  profileMode:
    enabled: true
    buttons:
      - name: Archives
        url: "/archives/"
      - name: Github
        url: "https://stratagem360ai.github.io/AIGenesis/archives"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
cover:
  relative: false # To use relative path for cover image, used in hugo Page-bundles
params:
  cover:
    responsiveImages: false
params:
  cover:
    linkFullImages: true
params:
  ShowShareButtons: true
params:
  ShowReadingTime: true
params:
  ShowToc: true
params:
  TocOpen: true
params:
  ShowBreadCrumbs: true
params:
  ShowPostNavLinks: true
params:
  ShowCodeCopyButtons: true
params:
  author: ["Me", "You"]
params:
  comments: false
  menu:
  main:
      identifier: about
      name: about
      url: "/content/"
      weight: 10
      identifier: contact
      name: contact
      url: /content/
      weight: 10
      identifier: tags
      name: tags
      url: /tags/
      weight: 20

